/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId/index'
import { Route as FolderFolderIdIndexRouteImport } from './routes/folder/$folderId/index'

const LayoutRoute = LayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
    id: '/login/',
    path: '/login/',
    getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutRoute,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
    id: '/project/$projectId/',
    path: '/project/$projectId/',
    getParentRoute: () => rootRouteImport,
} as any)
const FolderFolderIdIndexRoute = FolderFolderIdIndexRouteImport.update({
    id: '/folder/$folderId/',
    path: '/folder/$folderId/',
    getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
    '/': typeof LayoutIndexRoute
    '/login': typeof LoginIndexRoute
    '/folder/$folderId': typeof FolderFolderIdIndexRoute
    '/project/$projectId': typeof ProjectProjectIdIndexRoute
}
export interface FileRoutesByTo {
    '/': typeof LayoutIndexRoute
    '/login': typeof LoginIndexRoute
    '/folder/$folderId': typeof FolderFolderIdIndexRoute
    '/project/$projectId': typeof ProjectProjectIdIndexRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    '/_layout': typeof LayoutRouteWithChildren
    '/_layout/': typeof LayoutIndexRoute
    '/login/': typeof LoginIndexRoute
    '/folder/$folderId/': typeof FolderFolderIdIndexRoute
    '/project/$projectId/': typeof ProjectProjectIdIndexRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths: '/' | '/login' | '/folder/$folderId' | '/project/$projectId'
    fileRoutesByTo: FileRoutesByTo
    to: '/' | '/login' | '/folder/$folderId' | '/project/$projectId'
    id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/login/'
    | '/folder/$folderId/'
    | '/project/$projectId/'
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    LayoutRoute: typeof LayoutRouteWithChildren
    LoginIndexRoute: typeof LoginIndexRoute
    FolderFolderIdIndexRoute: typeof FolderFolderIdIndexRoute
    ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/_layout': {
            id: '/_layout'
            path: ''
            fullPath: ''
            preLoaderRoute: typeof LayoutRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/login/': {
            id: '/login/'
            path: '/login'
            fullPath: '/login'
            preLoaderRoute: typeof LoginIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/_layout/': {
            id: '/_layout/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof LayoutIndexRouteImport
            parentRoute: typeof LayoutRoute
        }
        '/project/$projectId/': {
            id: '/project/$projectId/'
            path: '/project/$projectId'
            fullPath: '/project/$projectId'
            preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        '/folder/$folderId/': {
            id: '/folder/$folderId/'
            path: '/folder/$folderId'
            fullPath: '/folder/$folderId'
            preLoaderRoute: typeof FolderFolderIdIndexRouteImport
            parentRoute: typeof rootRouteImport
        }
    }
}

interface LayoutRouteChildren {
    LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
    LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
    LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
    LayoutRoute: LayoutRouteWithChildren,
    LoginIndexRoute: LoginIndexRoute,
    FolderFolderIdIndexRoute: FolderFolderIdIndexRoute,
    ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()